spring.application.name=TP_API_REST
application.security.jwt.secret=5GTHGGGUYTY87576GTYGRR09R8JDJGHDUFYG9DR8U9TDFUDTUUYUDIUFGUI
application.security.jwt.ttl-minutes:30
application.security.jwt.issuer:spring-security
server.port=8081